#ifndef NOTES_H
#define NOTES_H

static const char * const notes[] =
{
	"null",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Press R while scanning.",
	"Appearance Codes",
	"You need to go change \n\nyour eyes with the machine, accept changes and go again in the machine nand you will see your character with two ?'s for eyes.",
	"You need to go change \n\nyour eyes with the machine, accept changes and go again in the machine nand you will see your character with two ?'s for eyes.",
	"Type in the ID of the shirt that you want (Found on GBATemp) and press L to store it, and press R to change into the shirt.",
	"Misc Codes",
	"Go into the search bar, type in the item ID (found on GBATemp) press L to store it, press D Pad Up for a 'on table item' press D Pad Right for a 'regular item' and press D Pad Down for a 'carpet' item. Go inside and outside the room to see the change.",
	"Press R + D Pad Up to enable, press R + D Pad Down to disable.",
	"Open up your keyboard and press R to change some keys on the 'other' and 'special' tab to hidden change some keys to Nintendo symbols.",
	"Press L to get all emoticons.\n\nNote: Some emoticons are missing but they're replaced with hacked emoticons.",
	"Press L to place an object anywhere you want. Some furniture might disappear after saving."
};

#endif